config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :games, only: [:new, :create, :show, :update, :index]
  resources :pieces, only: [:create, :show, :edit, :update] 

  match 'pieces/promote' => 'pieces#promote_me', via: [:get, :post] 

  get 'mygames', to: 'static_pages#mygames'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end


  def mygames
    @mygames ||= get_mygames
  end

  def get_mygames
      Game.where(:user_id => current_user)
      .or(Game.where(:opponent_id => current_user))
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="hero">
  <br /><br/><br /><br/>
  <div class="frosty col-10 offset-1 text-center">
    <br /><br />
    <h1>endgame</h1>
    <br />
    <h2>play today, make your move</h2>
    <br />

    <% if user_signed_in? %>
      <%= link_to 'my games', mygames_path, class: 'btn btn-success' %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'new game', new_game_path, class: 'btn btn-success' %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'join game', games_path, class: 'btn btn-success' %>
    <% else %>
      <%= link_to 'log in', new_user_session_path, class: 'btn btn-success' %>&nbsp;&nbsp;&nbsp;
      <%= link_to 'sign up', new_user_registration_path, class: 'btn btn-success' %>
    <% end %>
    <br /><br /><br />
  </div>
</div>

<br />
<div class="col-10 offset-1">
  <h3>Play Some Chess Today...</h3>
  <br />
  <p>It's better than, playing checkers but not as good as backgammon!</p>
</div>

app/views/static_pages/mygames.html.erb
<div class="col-10 offset-1" >
  <br /><br />
  <h1>my games</h1>
  <div class="row">
    <div class="col-sm-3 col-12 available-subtitle">Game</div>
    <div class="col-sm-3 col-12 available-subtitle">Player 1</div>
    <div class="col-sm-3 col-12 available-subtitle">Player 2</div>
    <div class="col-sm-3 col-12 available-subtitle">Go to Game</div>
  </div>
  <div class="row">
    <% @mygames.each do |game| %>

      <div class="col-sm-3 col-12 float-left">
        <%= game.name %> 
      </div>
      <div class="col-sm-3 col-12">
        <%= game.user.email %>
      </div>
      <div class="col-sm-3 col-12">
        <% if game.opponent_id  == nil %>
          no opponent
        <% else %>
          <% player2 = User.where(:id => game.opponent_id).first %>
          <%= player2.email %>
        <% end %>
      </div>
      <div class="col-sm-3 col-12 float-right">
        <%= link_to 'continue', game_path(game.id), class: 'btn btn-success' %>
      </div>
      <br /><br />

    <% end %>
  </div>
</div>